/**
 * Multi-session protocol — message types and shared helpers.
 *
 * This module is intentionally side-effect free so it can be unit-tested
 * without touching the filesystem.
 */

import * as os from "node:os";

// =============================================================================
// Identity
// =============================================================================

/** Stable identity for a running pi process. */
export interface SessionIdentity {
	sessionId: string; // UUID from session file header (or generated for ephemeral)
	sessionFile: string | null; // path to JSONL, or null for ephemeral
	pid: number;
	hostname: string; // os.hostname() — disambiguate when agent dir is shared
	cwd: string;
	name: string; // display name from /name or session_info
	model: string | null; // "provider/id" or null
	thinkingLevel: string | null;
	status: SessionStatus;
	startedAt: string; // ISO
	lastHeartbeat: string; // ISO
}

export type SessionStatus = "starting" | "idle" | "busy";

/** Process registry — single source of truth keyed by `${hostname}:${pid}`. */
export interface Registry {
	version: 1;
	sessions: Record<string, SessionIdentity>; // key = "hostname:pid"
}

/** A process is "live" if its lastHeartbeat is within `staleMs`. */
export const HEARTBEAT_INTERVAL_MS = 10_000;
export const STALE_THRESHOLD_MS = 30_000; // 3 missed heartbeats

// =============================================================================
// Messages
// =============================================================================

export type MessageType = "notify" | "task" | "steer" | "request" | "reply" | "ack";

export interface MessageFrom {
	sessionId: string;
	name: string;
	pid: number;
}

export interface MessagePayload {
	text: string;
}

export interface MailboxMessage {
	id: string; // UUID v4, generated by sender
	type: MessageType;
	from: MessageFrom;
	to: string; // recipient sessionId
	payload: MessagePayload;
	replyTo?: string; // for reply/ack, references the prior message id
	timestamp: string; // ISO
	/** Optional expiry. Default TTL applied at read time. */
	ttlMs?: number;
	/** Set by recipient after handling. */
	status?: "pending" | "processed" | "failed";
	/** Filled when status === "failed". */
	error?: string;
}

/** Default time-to-live for messages. Older messages are dropped on read. */
export const MESSAGE_DEFAULT_TTL_MS = 60 * 60 * 1000; // 1 hour

// =============================================================================
// Sender identity
// =============================================================================

/**
 * Build the identity for the currently running pi process. Pulls hostname
 * and pid from the OS; sessionId / cwd / name / model must be supplied by
 * the caller (they come from the live pi context).
 */
export function buildIdentity(input: {
	sessionId: string;
	sessionFile: string | null;
	cwd: string;
	name: string;
	model: string | null;
	thinkingLevel: string | null;
	status: SessionStatus;
}): Omit<SessionIdentity, "startedAt" | "lastHeartbeat"> & { startedAt: string; lastHeartbeat: string } {
	const now = new Date().toISOString();
	return {
		sessionId: input.sessionId,
		sessionFile: input.sessionFile,
		pid: process.pid,
		hostname: os.hostname(),
		cwd: input.cwd,
		name: input.name,
		model: input.model,
		thinkingLevel: input.thinkingLevel,
		status: input.status,
		startedAt: now,
		lastHeartbeat: now,
	};
}

/** Composite key for the registry: `hostname:pid`. */
export function registryKey(hostname: string, pid: number): string {
	return `${hostname}:${pid}`;
}

/** Extract hostname:pid from a key. */
export function parseRegistryKey(key: string): { hostname: string; pid: number } {
	const idx = key.indexOf(":");
	if (idx < 0) {
		throw new Error(`Invalid registry key: ${key}`);
	}
	return {
		hostname: key.slice(0, idx),
		pid: Number.parseInt(key.slice(idx + 1), 10),
	};
}

// =============================================================================
// Session addressing
// =============================================================================

/**
 * Resolve a partial session id or display name to a unique identity.
 * Returns null if no match, or an error string if ambiguous.
 */
export function resolveSessionRef(
	registry: Registry,
	ref: string,
): { match: SessionIdentity; ambiguous?: false } | { ambiguous: true; candidates: SessionIdentity[] } | null {
	const trimmed = ref.trim();
	if (!trimmed) return null;

	// 1. Try exact sessionId match.
	for (const entry of Object.values(registry.sessions)) {
		if (entry.sessionId === trimmed) return { match: entry };
	}

	// 2. Try prefix match on sessionId.
	const prefixMatches = Object.values(registry.sessions).filter(
		(entry) => entry.sessionId.startsWith(trimmed) || entry.sessionId.replace(/-/g, "").startsWith(trimmed),
	);
	if (prefixMatches.length === 1) return { match: prefixMatches[0] };
	if (prefixMatches.length > 1) return { ambiguous: true, candidates: prefixMatches };

	// 3. Try exact display-name match.
	const nameMatches = Object.values(registry.sessions).filter((entry) => entry.name === trimmed);
	if (nameMatches.length === 1) return { match: nameMatches[0] };
	if (nameMatches.length > 1) return { ambiguous: true, candidates: nameMatches };

	// 4. Try case-insensitive display-name match.
	const ci = trimmed.toLowerCase();
	const ciMatches = Object.values(registry.sessions).filter((entry) => entry.name.toLowerCase() === ci);
	if (ciMatches.length === 1) return { match: ciMatches[0] };
	if (ciMatches.length > 1) return { ambiguous: true, candidates: ciMatches };

	return null;
}

/** Compact form of a session id for display (first 8 hex chars). */
export function shortSessionId(sessionId: string): string {
	// UUIDs use hex+hyphen; keep first 8 chars. For non-UUIDs, just first 8.
	return sessionId.slice(0, 8);
}

// =============================================================================
// UUID generation
// =============================================================================

/**
 * Generate a UUID v4. Avoids importing a uuid library — Node 24 has
 * `crypto.randomUUID` built in.
 */
export function uuid(): string {
	// Node 19+ has crypto.randomUUID; we target Node 24+ for pi, so this is safe.
	return globalThis.crypto.randomUUID();
}
